### ISSUE TITLE
what is the unit of the LiDAR velocity ?

### ISSUE THREAD

**Issue by kahowang** [minwoo0611/Awesome-3D-LiDAR-Datasets#5]
Hi minwoo,
I've been trying your  `HeLiPR Dataset` recently, but I have a question: 

What is the unit of velocity in the `Aeva` dataset? I tried `Bridege02` dataset, imitating the read *.bin function in `helipr_file_player`, I read a frame of `Aeva` pointcloud moving on the bridge, but when I printed the data, I found that most of the speed values were close to 0. like (-0.117059, -0.0196886, -0.165367...).

 At the same time I look at the velocity distribution of the points as. 
`Velocity Distribution Intervals with Point Counts: `
`Interval 1: -0.485863 to -0.436184 - Points: 26`
`Interval 2: -0.436184 to -0.386506 - Points: 65`
`Interval 3: -0.386506 to -0.336827 - Points: 130`
`Interval 4: -0.336827 to -0.287149 - Points: 311`
`Interval 5: -0.287149 to -0.23747 - Points: 799`
`Interval 6: -0.23747 to -0.187792 - Points: 1555`
`Interval 7: -0.187792 to -0.138113 - Points: 3016`
`Interval 8: -0.138113 to -0.0884346 - Points: 4892`
`Interval 9: -0.0884346 to -0.0387561 - Points: 6456`
`Interval 10: -0.0387561 to 0.0109224 - Points: 7278`
`Interval 11: 0.0109224 to 0.0606009 - Points: 6336`
`Interval 12: 0.0606009 to 0.110279 - Points: 4598`
`Interval 13: 0.110279 to 0.159958 - Points: 2829`
`Interval 14: 0.159958 to 0.209636 - Points: 1530`
`Interval 15: 0.209636 to 0.259315 - Points: 749`
`Interval 16: 0.259315 to 0.308994 - Points: 397`
`Interval 17: 0.308994 to 0.358672 - Points: 238`
`Interval 18: 0.358672 to 0.408351 - Points: 88`
`Interval 19: 0.408351 to 0.458029 - Points: 33`
`Interval 20: 0.458029 to 0.507708 - Points: 24`

In my opinion the unit of speed should not be m/s. Because most of the objects on the bridge are stationary, and the car body is relatively fast at this time. Could you please give me some  suggestions? The following datasets are analyzed in detail.

Looking forward for your reply~
Kaho

[1690786996161895376.zip](https://github.com/minwoo0611/Awesome-3D-LiDAR-Datasets/files/13345929/1690786996161895376.zip)

**Comment by minwoo0611** [comment]
Hello, @kahowang 

Thank you for reaching out regarding the HeLiPR Dataset and the Aeva LiDAR data. The velocity values in the Aeva dataset are indeed measured in meters per second (m/s). It's important to note that these are absolute velocities, not relative velocities. The readings close to zero suggest that most objects in the dataset, particularly in the bridge scenario, are stationary or moving very slowly.

Should you have any more questions or encounter issues specific to the HeLiPR dataset, please feel free to post them in the helipr_file_player repository for more specialized guidance.

Thank you for your interest in the dataset!

Best regards,
