### ISSUE TITLE
Add Column for Vehicle Type Used

### ISSUE THREAD

**Issue by jorgeffonte** [minwoo0611/Awesome-3D-LiDAR-Datasets#6]
Hello,

Firstly, thank you for maintaining such an extensive and useful list of 3D LiDAR datasets. I have a suggestion that I believe would enhance the usability of this repository.

It would be beneficial to add an additional column to the dataset table to indicate the type of vehicle used for data collection. Knowing the vehicle type can provide valuable context and help users better understand the dataset's characteristics and potential applications.

Thank you for considering this suggestion. I appreciate all the hard work that has gone into this repository.

Best regards,

**Comment by minwoo0611** [comment]
Hello, @jorgeffonte,

Thank you for your valuable suggestion! I completely agree that knowing the type of vehicle used for data collection, in addition to the sensors used in the datasets, is crucial for many tasks. This information can provide important context for users to better understand the characteristics and potential applications of the datasets.

Currently, I'm involved in a project and working on some papers, so it may take some time to make the changes. However, once I have completed that, I plan to update the repository with recent datasets and include more detailed information, such as the vehicle type used in each dataset.

Thank you again for your input, and I appreciate your understanding and support.

Best regards.
Minwoo
